[package]
name = "use_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "use_env"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dirs = "4.0"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
